--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 720.0000, height = 1280.0000})

--Create bg
local bg = ccui.ImageView:create()
bg:ignoreContentAdaptWithSize(false)
bg:loadTexture("tetris2048/res/other/BG.jpg",0)
bg:setLayoutComponentEnabled(true)
bg:setName("bg")
bg:setTag(4)
bg:setCascadeColorEnabled(true)
bg:setCascadeOpacityEnabled(true)
bg:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 720.0000, height = 1280.0000})
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setStretchWidthEnabled(true)
layout:setStretchHeightEnabled(true)
Layer:addChild(bg)

--Create logo
local logo = ccui.ImageView:create()
logo:ignoreContentAdaptWithSize(false)
logo:loadTexture("tetris2048/res/other/Logo.png",0)
logo:setLayoutComponentEnabled(true)
logo:setName("logo")
logo:setTag(5)
logo:setCascadeColorEnabled(true)
logo:setCascadeOpacityEnabled(true)
logo:setPosition(360.0000, 1024.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(logo)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.8000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.3836)
layout:setSize({width = 720.0000, height = 491.0000})
layout:setTopMargin(10.5000)
layout:setBottomMargin(778.4999)
Layer:addChild(logo)

--Create playBtn
local playBtn = ccui.ImageView:create()
playBtn:ignoreContentAdaptWithSize(false)
playBtn:loadTexture("tetris2048/res/other/Play.png",0)
playBtn:setLayoutComponentEnabled(true)
playBtn:setName("playBtn")
playBtn:setTag(8)
playBtn:setCascadeColorEnabled(true)
playBtn:setCascadeOpacityEnabled(true)
playBtn:setPosition(360.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(playBtn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3833)
layout:setPercentHeight(0.2156)
layout:setSize({width = 276.0000, height = 276.0000})
layout:setLeftMargin(222.0000)
layout:setRightMargin(222.0000)
layout:setTopMargin(502.0000)
layout:setBottomMargin(502.0000)
Layer:addChild(playBtn)

--Create buttonView
local buttonView = ccui.Layout:create()
buttonView:ignoreContentAdaptWithSize(false)
buttonView:setClippingEnabled(false)
buttonView:setBackGroundColorOpacity(102)
buttonView:setLayoutComponentEnabled(true)
buttonView:setName("buttonView")
buttonView:setTag(14)
buttonView:setCascadeColorEnabled(true)
buttonView:setCascadeOpacityEnabled(true)
buttonView:setAnchorPoint(0.5000, 0.5000)
buttonView:setPosition(360.0000, 320.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(buttonView)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2500)
layout:setPercentWidth(0.9444)
layout:setPercentHeight(0.0898)
layout:setSize({width = 680.0000, height = 115.0000})
layout:setLeftMargin(20.0000)
layout:setRightMargin(20.0000)
layout:setTopMargin(902.5000)
layout:setBottomMargin(262.5000)
Layer:addChild(buttonView)

--Create settingBtn
local settingBtn = ccui.ImageView:create()
settingBtn:ignoreContentAdaptWithSize(false)
settingBtn:loadTexture("tetris2048/res/other/Settings.png",0)
settingBtn:setLayoutComponentEnabled(true)
settingBtn:setName("settingBtn")
settingBtn:setTag(12)
settingBtn:setCascadeColorEnabled(true)
settingBtn:setCascadeOpacityEnabled(true)
settingBtn:setPosition(204.0000, 57.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(settingBtn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.3000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.2882)
layout:setPercentHeight(1.8000)
layout:setSize({width = 196.0000, height = 207.0000})
layout:setLeftMargin(106.0000)
layout:setRightMargin(378.0000)
layout:setTopMargin(-46.0000)
layout:setBottomMargin(-46.0000)
buttonView:addChild(settingBtn)

--Create rankBtn
local rankBtn = ccui.ImageView:create()
rankBtn:ignoreContentAdaptWithSize(false)
rankBtn:loadTexture("tetris2048/res/other/PlayerStat.png",0)
rankBtn:setLayoutComponentEnabled(true)
rankBtn:setName("rankBtn")
rankBtn:setTag(10)
rankBtn:setCascadeColorEnabled(true)
rankBtn:setCascadeOpacityEnabled(true)
rankBtn:setPosition(476.0000, 57.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(rankBtn)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.7000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.2882)
layout:setPercentHeight(1.8000)
layout:setSize({width = 196.0000, height = 207.0000})
layout:setLeftMargin(378.0000)
layout:setRightMargin(106.0000)
layout:setTopMargin(-46.0000)
layout:setBottomMargin(-46.0000)
buttonView:addChild(rankBtn)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

