
local K = {}
local COOKIE_KEYS = K

K.AUTO_BUY_IN = "AUTO_BUY_IN"
K.AUTO_SIT = "AUTO_SIT"
K.SHOCK = "SHOCK"
K.VOLUME_SOUND = "VOLUME_SOUND"
K.VOLUME_MUSIC = "VOLUME_MUSIC"
K.SOUND_TYPE = "SOUND_TYPE" --男声"male" 女声"female"
--


K.LAST_LOGIN_TYPE              = "LAST_LOGIN_TYPE"
K.LAST_LOGIN_MID               = "LAST_LOGIN_MID"
K.LAST_LOGIN_TOKEN               = "LAST_LOGIN_TOKEN"
K.LOGIN_MTKEY                  = "LOGIN_MTKEY"
K.LOGIN_SESSKEY                = "SESSKEY"
K.LOGINED_DEVICE               = "LOGINED_DEVICE"
K.CREATE_SELECT_REMENBER 	   = "CREATE_SELECT_REMENBER"
K.SELECT_CITY					= "SELECT_CITY"
K.SELECT_CITY_GROUP				= "SELECT_CITY_GROUP"
K.PLAYED_GAMEIDS				= "PLAYED_GAMEIDS"
K.PLAYED_LEVELS                 = "PLAYED_LEVELS"

K.SELECT_HALL					= "SELECT_HALL"
K.GAME_HALL_TIP					= "GAME_HALL_TIP"
K.CLUB_TIP						= "CLUB_TIP"

return COOKIE_KEYS