
local DATA_KEYS = {}

DATA_KEYS.USER_DATA              = "USER_DATA"
DATA_KEYS.ROOM_INFO              = "ROOM_INFO"
DATA_KEYS.ROOM_CHAT_HISTORY      = "ROOM_CHAT_HISTORY"
DATA_KEYS.CURRENT_HALL_VIEW      = "CURRENT_HALL_VIEW"
DATA_KEYS.CURRENT_HALL_POSTION      = "CURRENT_HALL_POSTION"              --主页停留位置
DATA_KEYS.CURRENT_GAME_ID        = "CURRENT_GAME_ID"
DATA_KEYS.SIT_OR_STAND           = "SIT_OR_STAND"
DATA_KEYS.NEW_MESSAGE            = "NEW_MESSAGE"
DATA_KEYS.TABLE_CONF             = "TABLE_CONF" --场次配置
DATA_KEYS.SIGNAL_STRENGTH        = "SIGNAL_STRENGTH"
DATA_KEYS.FRIEND_DATA        	 = "FRIEND_DATA"
DATA_KEYS.QQ_VIP_DATA            = "QQ_VIP_DATA"
DATA_KEYS.START_UP_DATA          = "START_UP_DATA"
DATA_KEYS.BATTERY_LEVEL          = "BATTERY_LEVEL "    --电量百分比


DATA_KEYS.GAMES_LIST              = "GAMES_LIST"     --游戏列表

DATA_KEYS.TABLE_ID                = "DATA_KEYS_TABLE_ID"  --当前游戏的tableid
DATA_KEYS.ROOM_CODE               = "ROOM_CODE"
DATA_KEYS.ROOM_CODE               = "ROOM_CODE"
DATA_KEYS.CURRENTROUND            = "CURRENTROUND"
DATA_KEYS.TOTALROUND              = "TOTALROUND"
DATA_KEYS.GAME_LEVEL              = "DATA_KEYS_GAME_LEVEL"  --当前游戏的gamelevel
DATA_KEYS.GAME_ID              	  = "DATA_KEYS_GAME_ID"  --当前游戏的gameid
DATA_KEYS.PRIVATE_ROOM_ROUND      = "PRIVATE_ROOM_ROUND"  --创建私人房选择的局数
DATA_KEYS.BASE_CHIP               = "BASE_CHIP"  --当前游戏的底注
DATA_KEYS.SERVICE_FEE    	 	  = "SERVICE_FEE"  --当前游戏的台费
DATA_KEYS.MONEY_KIND    	 	  = "MONEY_KIND"  --当前游戏的货币类型（1=充值货币；2=游戏币；3=兑换币；4=积分）
DATA_KEYS.BANKRUPT_DATA 		  = "BANKRUPT_DATA"--房间T人破产信息
DATA_KEYS.CREATE_ROOM_SELECT 	  = "CREATE_ROOM_SELECT" --玩家在私人房结束之后，是否选择了创建房间

DATA_KEYS.HAS_MSG_DATA            = "HAS_MSG_DATA"

DATA_KEYS.MJ_HU_INFO_DATA         = "MJ_HU_INFO_DATA" --保存麻将的胡牌信息

DATA_KEYS.MJ_HU_INFO_DATA_CHECK   = "MJ_HU_INFO_DATA_CHECK" --检测保存麻将的胡牌信息

DATA_KEYS.NOTICE_DATA 			= "NOTICE_DATA" --广播消息存储器

DATA_KEYS.PLAY_BACK_FILE		= "PLAY_BACK_FILE" --回放数据存储器

DATA_KEYS.PLAY_BACK_DATA 	 	= "PLAY_BACK_DATA" --回放数据

DATA_KEYS.PLAY_BACK_MID	 		= "PLAY_BACK_MID" --回放视角mid

DATA_KEYS.GAME_SCENE_RECORDER		= "GAME_SCENE_RECORDER" --游戏场景回放录像

DATA_KEYS.CREATE_ROOM_SELECT_RADIO = "CREATE_ROOM_SELECT_RADIO" --私人房创建界面玩家选择存储器

DATA_KEYS.PRIVATE_CREATE_DATA        = "PRIVATE_CREATE_DATA"  --创建某个私人房的配置

DATA_KEYS.SELECT_CITY	=	"SELECT_CITY"			--选中的城市

DATA_KEYS.SELECT_GAME_ID = "SELECT_GAME_ID"			--玩家选中的游戏

DATA_KEYS.GAME_OVER_RECORD = "GAME_OVER_RECORD"			--战绩

DATA_KEYS.CHAT_DATA = "CHAT_DATA"			--聊天记录

DATA_KEYS.IS_NI_MING	= "IS_NI_MING"		--游戏内匿名


DATA_KEYS.IS_FIRST_LOGIN_PHP = "IS_FIRST_LOGIN_PHP"	--是否是第一次登录

DATA_KEYS.VOICE_RECORD_ENABLE_TIME_POINT = "VOICE_RECORD_ENABLE_TIME_POINT" -- 可以点击下一次录音（语音聊天）的时间点
DATA_KEYS.SHOW_PLAY_BACK_FLAG = "SHOW_PLAY_BACK_FLAG"   --回放触发标记



DATA_KEYS.H5_ACTIVITY_DATA = "H5_ACTIVITY_DATA" --H5 运营活动

return DATA_KEYS
