
local EVENT_NAMES = {}
local E = EVENT_NAMES

E.APP_ENTER_BACKGROUND = "APP_ENTER_BACKGROUND"
E.APP_ENTER_FOREGROUND = "APP_ENTER_FOREGROUND"
E.CHENGE_TABLEBG_WITH_ID = "ENTER_CHENGE_TABLEBG_WITH_ID"
E.CHENGE_CARD_FONT = "CHENGE_CARD_FONT"


E.HALL_LOGOUT_SUCC = "HALL_LOGOUT_SUCC"
E.ENTER_ROOM_WITH_DATA = "ENTER_ROOM_WITH_DATA"

-- 用户登录成功，用户登录失败
E.HALL_LOGIN_SUCC = "HALL_LOGIN_SUCC"
E.HALL_LOGIN_FAILED = "HALL_LOGIN_FAILED"


E.ENTER_GAME = "ENTER_GAME"

E.NETWORK_CHANGE = "NETWORK_CHANGE"
E.HANDLE_OPEN_URL = "HANDLE_OPEN_URL"

E.PLAY_BACK_DATA = "PLAY_BACK_DATA"

--活动次数
E.REFRESH_ROTARY_COUNT = "REFRESH_ROTARY_COUNT"

-- 刷新被邀请界面
E.REFRESH_ID_BEINVITE_VIEW = "REFRESH_ID_BEINVITE_VIEW"

return EVENT_NAMES
